server:
  port: 8060

spring:
  application:
    name: tkmybatis-demo
  datasource:
    druid:
      url: jdbc:mysql://10.58.11.13:3370/yuntu_340_2316?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&connectTimeout=5000&socketTimeout=5000&autoReconnect=true&maxReconnects=5&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: yuntu
      password: yuntu
      initial-size: 1
      max-active: 10
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - com.chenpp.spring.samples.tkmybatis.dao.IMapper
  notEmpty: true

mybatis:
  #  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    root: info